# Generated by Django 4.1 on 2022-09-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amarillas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('club', models.CharField(max_length=50)),
                ('amarilllas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Asistidores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('club', models.CharField(max_length=50)),
                ('asistencias', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Goleadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('club', models.CharField(max_length=50)),
                ('goles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('club', models.CharField(max_length=50)),
                ('rojas', models.IntegerField()),
            ],
        ),
    ]
