# Generated by Django 4.1 on 2022-09-05 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LigaFc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amarillas',
            old_name='amarilllas',
            new_name='amarillas',
        ),
    ]
