# Generated by Django 4.1 on 2022-09-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LigaFc', '0002_rename_amarilllas_amarillas_amarillas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asistidores',
            new_name='Asistencias',
        ),
    ]
